[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 12.5

[window]
dimensions = { columns = 120, lines = 31 }
opacity = 1.0
padding = { x = 4, y = 4 }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }

[colors.primary]
foreground = "#e8e8e8"
background = "#282c34"

[colors.cursor]
text = "#282c34"
cursor = "#e8e8e8"

[colors.selection]
text = "#e8e8e8"
background = "#3e4451"

[colors.normal]
black = "#393b44"
red = "#c94f6d"
green = "#81b29a"
yellow = "#dbc074"
blue = "#719cd6"
magenta = "#9d79d6"
cyan = "#63cdcf"
white = "#dfdfe0"

[colors.bright]
black = "#575860"
red = "#d16983"
green = "#8ebaa4"
yellow = "#e0c989"
blue = "#86abdc"
magenta = "#baa1e2"
cyan = "#7ad5d6"
white = "#e4e4e5"
