# -----------------------------
# Font
# -----------------------------
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.5

# -----------------------------
# Window (normal sized)
# -----------------------------
remember_window_size  no
initial_window_width  1200
initial_window_height 700

background_opacity 0.9

# -----------------------------
# Colors (Nord)
# -----------------------------
foreground #D8DEE9
background #2E3440

color0  #3B4252
color1  #BF616A
color2  #A3BE8C
color3  #EBCB8B
color4  #81A1C1
color5  #B48EAD
color6  #88C0D0
color7  #E5E9F0

color8  #4C566A
color9  #BF616A
color10 #A3BE8C
color11 #EBCB8B
color12 #81A1C1
color13 #B48EAD
color14 #8FBCBB
color15 #ECEFF4

# -----------------------------
# Scrolling
# -----------------------------
scrollback_lines 10000

# -----------------------------
# Cursor (FAT block)
# -----------------------------
cursor_shape               block
cursor                     #D8DEE9
cursor_text_color          #2E3440
cursor_beam_thickness      8.0
cursor_underline_thickness 8.0
cursor_blink_interval      0.5

# -----------------------------
# Mouse
# -----------------------------
copy_on_select yes
strip_trailing_spaces always
mouse_map middle release ungrabbed paste_from_selection
